server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://db.fvmrqnaajwwahgcgyzhx.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: Dasafego2007
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    jwtSecret: "kOZx/sJ7t/TWVG1qm2aXQ0gcqCu2Gym4UiaQZqj0l+c="
    jwtExpirationMs: 86400000