server:
  port: 8080

spring:
  datasource:
    # URL de conexión a Supabase (PostgreSQL)
    url: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.fvmrqnaajwwahgcgyzhx&password=Dasafego2007
    username: postgres.fvmrqnaajwwahgcgyzhx
    password: Dasafego2007
    driver-class-name: org.postgresql.Driver
  jpa:
    # Como ya creamos el script SQL manualmente, le decimos a Hibernate que NO altere las tablas
    hibernate:
      ddl-auto: validate 
    show-sql: true # Muestra el SQL en consola (útil para debug)
    properties:
      hibernate:
        format_sql: true


# Configuración personalizada para JWT
app:
  security:
    # Secreto de 256 bits (minimo) en Base64. (Usa uno fuerte en producción)
    jwtSecret: "arWbEyAPuZsTD5VcxSNVmFeATPB8P9IXgnTZMLWJjy4="
    jwtExpirationMs: 86400000 # 24 horas en milisegundos